const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "Wissam DeV";
const email = "email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "***********";
const retyprePassword = "Retype your password";
const retyprePasswordhint = "***********";
const name = "name";
const namehint = "enter Your name";
const forgetpass = "Forget Password";
const signUp = "Sign Up";
const login = "Log In";
const creteAcount = "Or, crete a new account";
const loginWith = "Log in with";
const privecyAndPolicy = "Privacy and Policy";
const termsAndCondation = "Terms and  Conditions";
const alreadyHaveAcount = "Alredy have an account?";
const serchingAnyThinf = "Search anything...";
const categories = "Categories",
    tody = "Today's Deal",
    flashseal = "Flash sale",
    topBrand = "Top Brand",
    topcategory = "Top Categoys",
    womenDress = "Women Dress",
    girlWatches = "Girl Watches",
    mobilephone = "Mobile Phone",
    boyGlases = "Boy Glases",
    tshirt = "T-Shirts",
    girlDesse = "Girl Dress",
    featuredProducr = "Featured Product",
    featuredCategory = "Featured Category";

const womenClothes = "Women Clothing",
    menClothes = "Men Clothing & fashion",
    compAcces = "Computer & Accesories",
    autoMobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "CellPhone & Tap",
    furniture = "Furniture";
